- name: NetApp Volume Creation Only
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - netapp.ontap
    - community.general

  vars:
    netapp_hostname: "192.168.0.102"
    netapp_username: "admin"
    netapp_password: "Netapp1!"
    vserver: "svm1"
    qtree_name: "qtreetest"
    volume_name: "vol1001"
    aggregate_name: "aggr1"
    volume_size: 5
    size_unit: "gb"
    snapshot_policy_name: "test_snap_policy"
    smb_share_name: "testShare"
    smb_user_or_group: "BUILTIN\\Administrators"

    export_policy_name: "exportPolicy"
    cifs_server_name: "data3"
    id_domain: "DEMO.NETAPP.COM"
    domain_login: "Administrator"
    domain_pwd: "Netapp1!"
    export_policy_rule_index: 11
    export_policy_client_match: "192.168.0.120"

    # Feature control flags
    create_snapshot_policy: true
    create_export_policy: false
    create_export_policy_rule: true
    create_volume: true
    enable_snapshot: true
    enable_nfs: true
    create_qtree: true
    manage_cifs_server: true
    create_smb_share: true
    create_smb_acl: true
    create_lun: false
    delete_volume: true

  roles:
    - role: /netapproles/new_volume_role

