---
- name: Create Export Policy
  netapp.ontap.na_ontap_export_policy:
    state: present
    name: "{{ export_policy_name }}"
    vserver: "{{ vserver }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    use_rest: always
    validate_certs: false
  when: create_export_policy | default(false)

