- name: Manage CIFS server (create/start/stop/delete)
  netapp.ontap.na_ontap_cifs_server:
    state: present                       # use 'absent' to delete
    name: "{{ cifs_server_name }}"
    vserver: "{{ vserver }}"
    service_state: started                # 'stopped' to stop, omit to just create
    domain: "{{ id_domain | default(omit) }}"      # only needed when creating
    admin_user_name: "{{ domain_login | default(omit) }}"
    admin_password: "{{ domain_pwd | default(omit) }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    use_rest: always
    https: true
    validate_certs: false
  when: manage_cifs_server | default(false)

