---
# tasks/create_smb_share.yml

- name: Create CIFS share - REST
  netapp.ontap.na_ontap_cifs:
    state: present
    name: "{{ smb_share_name }}"                     # CIFS share name
    path: "/{{ volume_name }}"                       # Path inside the volume
    vserver: "{{ vserver }}"                         # SVM name
    oplocks: true
    access_based_enumeration: true
    change_notify: true
    comment: "{{ smb_comment | default('Created via Ansible') }}"
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    use_rest: always
    https: true
    validate_certs: false

