- name: Ensure snapshot policy is applied
  na_ontap_volume:
    hostname: "{{ netapp_hostname }}"
    username: "{{ netapp_username }}"
    password: "{{ netapp_password }}"
    vserver: "{{ vserver }}"
    name: "{{ volume_name }}"
    snapshot_policy: "{{ snapshot_policy }}"
    use_rest: true
    validate_certs: false

